In [1]:
# ==========================================
# 1. Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
# ==========================================
# 2. Load Dataset
# ==========================================

df = pd.read_csv("../data/raw/Personalized_Diet_Recommendations.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
# ==========================================
# 3. Dataset Shape
# ==========================================

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.head()

Rows : 5000
Columns : 30

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Chronic_Disease,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Genetic_Risk_Factor,Allergies,Daily_Steps,Exercise_Frequency,Sleep_Hours,Alcohol_Consumption,Smoking_Habit,Dietary_Habits,Caloric_Intake,Protein_Intake,Carbohydrate_Intake,Fat_Intake,Preferred_Cuisine,Food_Aversions,Recommended_Calories,Recommended_Protein,Recommended_Carbs,Recommended_Fats,Recommended_Meal_Plan
0,P00001,56,Other,163,66,24.84,NaN,175,75,219,124,No,NaN,11452,5,7.6,No,Yes,Vegetarian,2593,105,179,143,Western,NaN,2150,108,139,145,High-Protein Diet
1,P00002,69,Female,171,114,38.99,NaN,155,72,208,72,No,NaN,12962,1,6.3,Yes,No,Vegetarian,1852,69,315,75,Mediterranean,NaN,1527,74,266,80,Balanced Diet
2,P00003,46,Female,172,119,40.22,NaN,137,101,171,145,No,Gluten Intolerance,7898,3,9.9,No,No,Vegetarian,2737,183,103,148,Western,Sweet,2359,180,145,143,High-Protein Diet
3,P00004,32,Female,197,118,30.41,NaN,148,91,258,235,No,Nut Allergy,6602,5,4.2,No,No,Vegetarian,3289,135,371,120,Western,NaN,2858,137,378,135,High-Protein Diet
4,P00005,60,Female,156,109,44.79,Hypertension,160,109,260,248,Yes,NaN,9810,2,9.0,No,No,Regular,2405,167,298,48,Indian,Spicy,1937,166,317,56,High-Protein Diet

In [4]:
# ==========================================
# 4. Column Names
# ==========================================

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

1. Patient_ID
2. Age
3. Gender
4. Height_cm
5. Weight_kg
6. BMI
7. Chronic_Disease
8. Blood_Pressure_Systolic
9. Blood_Pressure_Diastolic
10. Cholesterol_Level
11. Blood_Sugar_Level
12. Genetic_Risk_Factor
13. Allergies
14. Daily_Steps
15. Exercise_Frequency
16. Sleep_Hours
17. Alcohol_Consumption
18. Smoking_Habit
19. Dietary_Habits
20. Caloric_Intake
21. Protein_Intake
22. Carbohydrate_Intake
23. Fat_Intake
24. Preferred_Cuisine
25. Food_Aversions
26. Recommended_Calories
27. Recommended_Protein
28. Recommended_Carbs
29. Recommended_Fats
30. Recommended_Meal_Plan

In [5]:
# ==========================================
# 5. Dataset Information
# ==========================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient_ID                5000 non-null   object
 1   Age                       5000 non-null   int64
 2   Gender                    5000 non-null   object
 3   Height_cm                 5000 non-null   int64
 4   Weight_kg                 5000 non-null   int64
 5   BMI                       5000 non-null   float64
 6   Chronic_Disease           2957 non-null   object
 7   Blood_Pressure_Systolic   5000 non-null   int64
 8   Blood_Pressure_Diastolic  5000 non-null   int64
 9   Cholesterol_Level         5000 non-null   int64
 10  Blood_Sugar_Level         5000 non-null   int64
 11  Genetic_Risk_Factor       5000 non-null   object
 12  Allergies                 1503 non-null   object
 13  Daily_Steps               5000 non-null   int64
 14  Exercise_Frequency        5000 non-null   int64
 15  Sleep_Hours               5000 non-null   float64
 16  Alcohol_Consumption       5000 non-null   object
 17  Smoking_Habit             5000 non-null   object
 18  Dietary_Habits            5000 non-null   object
 19  Caloric_Intake            5000 non-null   int64
 20  Protein_Intake            5000 non-null   int64
 21  Carbohydrate_Intake       5000 non-null   int64
 22  Fat_Intake                5000 non-null   int64
 23  Preferred_Cuisine         5000 non-null   object
 24  Food_Aversions            3775 non-null   object
 25  Recommended_Calories      5000 non-null   int64
 26  Recommended_Protein       5000 non-null   int64
 27  Recommended_Carbs         5000 non-null   int64
 28  Recommended_Fats          5000 non-null   int64
 29  Recommended_Meal_Plan     5000 non-null   object
dtypes: float64(2), int64(17), object(11)
memory usage: 1.1+ MB

In [6]:
# ==========================================
# 6. Statistical Summary
# ==========================================

df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,5000.0,48.805600,17.906991,18.00,34.00,49.00,64.0000,79.00
Height_cm,5000.0,174.244000,14.229173,150.00,162.00,174.00,186.0000,199.00
Weight_kg,5000.0,84.366200,20.181030,50.00,67.00,84.00,102.0000,119.00
BMI,5000.0,28.353134,8.297745,12.63,21.85,27.64,33.8125,52.89
Blood_Pressure_Systolic,5000.0,133.982400,26.216215,90.00,111.00,133.00,157.0000,179.00
Blood_Pressure_Diastolic,5000.0,89.735800,17.283025,60.00,75.00,90.00,105.0000,119.00
Cholesterol_Level,5000.0,224.297800,42.918923,150.00,187.00,224.00,261.0000,299.00
Blood_Sugar_Level,5000.0,159.330200,52.149430,70.00,114.00,160.00,204.0000,249.00
Daily_Steps,5000.0,8458.922800,3742.408853,2004.00,5278.75,8452.00,11671.7500,14997.00
Exercise_Frequency,5000.0,2.978200,2.001431,0.00,1.00,3.00,5.0000,6.00
Sleep_Hours,5000.0,7.019680,1.716133,4.00,5.60,7.00,8.5000,10.00
Caloric_Intake,5000.0,2347.350200,659.880146,1200.00,1777.00,2350.50,2921.2500,3499.00
Protein_Intake,5000.0,124.781800,43.280037,50.00,87.00,126.00,162.0000,199.00
Carbohydrate_Intake,5000.0,248.590000,86.535683,100.00,175.00,249.00,325.0000,399.00
Fat_Intake,5000.0,84.522600,37.495091,20.00,52.00,85.00,116.0000,149.00
Recommended_Calories,5000.0,2046.236000,671.380142,725.00,1478.00,2044.00,2621.0000,3372.00
Recommended_Protein,5000.0,129.287000,43.914252,40.00,92.00,129.00,166.0000,218.00
Recommended_Carbs,5000.0,248.328600,91.152909,50.00,173.00,246.00,324.0000,447.00
Recommended_Fats,5000.0,89.029400,38.336083,10.00,56.00,89.00,121.0000,168.00

In [7]:
# ==========================================
# 7. Missing Values
# ==========================================

missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

Allergies          3497
Chronic_Disease    2043
Food_Aversions     1225
dtype: int64

In [8]:
# ==========================================
# 8. Duplicate Rows
# ==========================================

duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [9]:
# ==========================================
# 9. Data Types
# ==========================================

df.dtypes

Patient_ID                   object
Age                           int64
Gender                       object
Height_cm                     int64
Weight_kg                     int64
BMI                         float64
Chronic_Disease              object
Blood_Pressure_Systolic       int64
Blood_Pressure_Diastolic      int64
Cholesterol_Level             int64
Blood_Sugar_Level             int64
Genetic_Risk_Factor          object
Allergies                    object
Daily_Steps                   int64
Exercise_Frequency            int64
Sleep_Hours                 float64
Alcohol_Consumption          object
Smoking_Habit                object
Dietary_Habits               object
Caloric_Intake                int64
Protein_Intake                int64
Carbohydrate_Intake           int64
Fat_Intake                    int64
Preferred_Cuisine            object
Food_Aversions               object
Recommended_Calories          int64
Recommended_Protein           int64
Recommended_Carbs             int64
Recommended_Fats              int64
Recommended_Meal_Plan        object
dtype: object

In [10]:
# ==========================================
# 10. Numerical and Categorical Features
# ==========================================

numerical_columns = df.select_dtypes(include=np.number).columns

categorical_columns = df.select_dtypes(include="object").columns

print("Numerical Features")
print(numerical_columns)

print()

print("Categorical Features")
print(categorical_columns)

Numerical Features
Index(['Age', 'Height_cm', 'Weight_kg', 'BMI', 'Blood_Pressure_Systolic',
       'Blood_Pressure_Diastolic', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Daily_Steps', 'Exercise_Frequency', 'Sleep_Hours', 'Caloric_Intake',
       'Protein_Intake', 'Carbohydrate_Intake', 'Fat_Intake',
       'Recommended_Calories', 'Recommended_Protein', 'Recommended_Carbs',
       'Recommended_Fats'],
      dtype='object')

Categorical Features
Index(['Patient_ID', 'Gender', 'Chronic_Disease', 'Genetic_Risk_Factor',
       'Allergies', 'Alcohol_Consumption', 'Smoking_Habit', 'Dietary_Habits',
       'Preferred_Cuisine', 'Food_Aversions', 'Recommended_Meal_Plan'],
      dtype='object')

In [11]:
# ==========================================
# 11. Unique Values
# ==========================================

for col in categorical_columns:
    print("="*50)
    print(col)
    print(df[col].unique())

==================================================
Patient_ID
['P00001' 'P00002' 'P00003' ... 'P04998' 'P04999' 'P05000']
==================================================
Gender
['Other' 'Female' 'Male']
==================================================
Chronic_Disease
[nan 'Hypertension' 'Diabetes' 'Heart Disease' 'Obesity']
==================================================
Genetic_Risk_Factor
['No' 'Yes']
==================================================
Allergies
[nan 'Gluten Intolerance' 'Nut Allergy' 'Lactose Intolerance']
==================================================
Alcohol_Consumption
['No' 'Yes']
==================================================
Smoking_Habit
['Yes' 'No']
==================================================
Dietary_Habits
['Vegetarian' 'Regular' 'Keto' 'Vegan']
==================================================
Preferred_Cuisine
['Western' 'Mediterranean' 'Indian' 'Asian']
==================================================
Food_Aversions
[nan 'Sweet' 'Spicy' 'Salty']
==================================================
Recommended_Meal_Plan
['High-Protein Diet' 'Balanced Diet' 'Low-Fat Diet' 'Low-Carb Diet']

## Initial Observations

- Dataset contains 5000 records.
- No duplicate records found.
- Some columns contain missing values.
- Most features are numerical.
- Recommended_Meal_Plan appears to be the classification target.
- Recommended_Calories appears to be the regression target.

# Initial Observations

- The dataset contains **5000 patient records** and **30 features**.
- There are **no duplicate records**, indicating good data quality.
- The dataset contains **19 numerical** and **11 categorical** features.
- Missing values are present in **Chronic_Disease**, **Allergies**, and **Food_Aversions**.
- Missing values appear to represent the absence of a condition rather than missing information.
- `Patient_ID` is a unique identifier and should be removed before model training.
- `Recommended_Calories` will be used as the **regression target**.
- `Recommended_Meal_Plan` will be used as the **classification target**.
- Health-related variables such as BMI, Blood Sugar, Cholesterol, Blood Pressure, Daily Steps, Exercise Frequency, and Dietary Habits are expected to be strong predictors.
- The dataset is well-structured and suitable for building a hybrid Machine Learning and Expert System for personalized diet recommendations.